'use client';
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from 'react';
import { createGame, transition, SAVE_KEY, BEST_KEY, MAX_LIGHT, LABELS, SYMBOLS, enemyOf, suggestedPlay, playKind, returnCost, scoreDetails, restoreGame, type Action, type Game, type Sigil, type Room } from './game';
const card=(id:string)=>`./cards/${id}.webp`;
const roomName=(r:Room)=>({monster:'モンスターの道',corridor:'静かな道',slime:'ぬめる道',spring:'灯りのある道',sword:'伝説の剣の部屋',boss:'ラスボスの部屋',ambush:'人影のある道',entrance:'入口'}[r.kind]);
const roomHint=(r:Room)=>({monster:'仲間を増やすチャンス',corridor:'何も起きずに進める',slime:'足跡が消えるので注意',spring:'灯りが6回復する',sword:'仲間3体で剣を抜ける',boss:'倒せば宝箱を開けられる',ambush:'カード1枚で足止め突破',entrance:'ここに帰れば生還'}[r.kind]);
const roomGlyph=(r:Room)=>({monster:'⚔',corridor:'→',slime:'≈',spring:'✧',sword:'⚔',boss:'♜',ambush:'！',entrance:'⌂'}[r.kind]);
function Combo({cards}:{cards:Sigil[]}){return <span className="combo-cards">{cards.map((s,i)=><span className={'sigil '+s} key={i}>{SYMBOLS[s]} {LABELS[s]}{i<cards.length-1?' ＋':''}</span>)}</span>}
export default function Home(){
 const [g,setG]=useState<Game>(()=>createGame());const [loaded,setLoaded]=useState(false);const [selected,setSelected]=useState<number[]>([]);const [modal,setModal]=useState<'help'|'log'|'restart'|'card'|null>(null);const [sound,setSound]=useState(false);const [best,setBest]=useState(0);const [saveOK,setSaveOK]=useState(true);const [hint,setHint]=useState('');const [copied,setCopied]=useState(false);const audio=useRef<AudioContext|null>(null);const dialog=useRef<HTMLDialogElement|null>(null);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Restore browser storage after server hydration.
 useEffect(()=>{let restored:Game|null=null;let record=0;try{restored=restoreGame(localStorage.getItem(SAVE_KEY));record=Number(localStorage.getItem(BEST_KEY))||0}catch{setSaveOK(false)}if(restored)setG(restored);setBest(Math.min(100,Math.max(0,record)));setLoaded(true)},[]); // Restore only this game's device-local save.
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Reflect storage availability and committed best record.
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(g));if(g.phase==='won'){const n=scoreDetails(g).total;const old=Number(localStorage.getItem(BEST_KEY))||0;if(n>old){localStorage.setItem(BEST_KEY,String(n));setBest(n)}}}catch{setSaveOK(false)}},[g,loaded]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 useEffect(()=>()=>{void audio.current?.close()},[]);
 const tone=(success=false)=>{if(!sound||!audio.current)return;const ctx=audio.current;void ctx.resume();const t=ctx.currentTime;[0,...(success?[1,2]:[])].forEach((n)=>{const o=ctx.createOscillator(),v=ctx.createGain();o.type='sine';o.frequency.value=[392,493.88,587.33][n];v.gain.setValueAtTime(.0001,t+n*.1);v.gain.exponentialRampToValueAtTime(.08,t+n*.1+.01);v.gain.exponentialRampToValueAtTime(.0001,t+n*.1+.18);o.connect(v);v.connect(ctx.destination);o.start(t+n*.1);o.stop(t+n*.1+.2)})};
 const act=(action:Action)=>{const next=transition(g,{...action,turn:g.turn});if(next===g)return;setG(current=>transition(current,{...action,turn:g.turn}));setSelected([]);setHint('');tone(next.phase==='won'||next.captured.length>g.captured.length||next.boss&&!g.boss)};
 const newGame=()=>{const data=new Uint32Array(1);crypto.getRandomValues(data);setG(transition(createGame(data[0]),{type:'start'}));setSelected([]);setHint('');setModal(null);setCopied(false)};
 const toggleSound=()=>{if(!sound){try{audio.current??=new AudioContext();void audio.current.resume();setSound(true)}catch{setHint('このブラウザでは音を再生できません。')}}else setSound(false)};
 const active=g.phase!=='ready', ended=['won','lost'].includes(g.phase), enemy=enemyOf(g), combo=g.battle&&enemy?enemy.combo[g.battle.step]:[], scored=scoreDetails(g), cost=returnCost(g), suggested=suggestedPlay(g);
 const share=async()=>{const text=`10歩ダンジョン ひとり旅｜${g.phase==='won'?`褒章${scored.total}個を持って生還！`:'次こそ、お宝を持ち帰る。'}\nhttps://uryoutamomo.github.io/ten-step-dungeon-solo/`;try{if(navigator.share){await navigator.share({title:'10歩ダンジョン ひとり旅',text})}else{await navigator.clipboard.writeText(text);setCopied(true)}}catch{setCopied(false)}};
 return <main className={'shell '+(active?'playing':'')}>
  <header className="topbar"><a className="brand" href="./" aria-label="10歩ダンジョン ひとり旅">10歩ダンジョン <span>ひとり旅</span></a><div className="header-actions"><button className="icon-button" onClick={toggleSound} aria-pressed={sound} aria-label={sound?'効果音を切る':'効果音を入れる'}>{sound?'♪ ON':'♪ OFF'}</button><button className="icon-button" onClick={()=>setModal('help')} aria-label="遊び方">？</button></div></header>
  {!active?<section className="welcome"><p className="eyebrow">小さな迷宮、大きなおみやげ。</p><h1>あと一歩、<br/>欲ばってみる？</h1><p className="intro">剣と盾と魔法を手に、10歩先の宝物へ。<br/>でも、帰るまでが冒険です。</p><div className="card-fan"><img src={card('sword')} alt="剣をふりおろすカード"/><img src={card('gold')} alt="金銀財宝カード"/><img src={card('magic')} alt="魔法をかけるカード"/></div><button className="primary" onClick={newGame} disabled={!loaded}>扉を開ける <span>→</span></button><p className="subtle">ひとり用 · タップで操作 · 途中で閉じても続きから</p>{best>0&&<p className="record">これまでの最高記録　✧ {best}個</p>}<button className="text-button" onClick={()=>setModal('help')}>はじめての方へ — 遊び方を見る</button></section>:
  <div className="journey">
   <div className="status-row"><div className={'light-stat '+(g.light<=cost+3?'low':'')}><span className="stat-label">✧ 残りの灯り</span><strong>{g.light}<small> / {MAX_LIGHT}</small></strong><div className="light-bar"><i style={{width:`${g.light/MAX_LIGHT*100}%`}}/></div></div><div><span className="stat-label">仲間</span><strong>{g.captured.length}<small> 体</small></strong></div><div><span className="stat-label">持ち帰れば</span><strong>{scored.total}<small> 褒章</small></strong></div><button className="bag" onClick={()=>setModal('log')} aria-label="持ち物と冒険の記録">▤<span>記録</span></button></div>
   <nav className="trail" aria-label="入口から10歩までの地図">{Array.from({length:11},(_,i)=><div key={i} className={'trail-step '+(i===g.pos?'current ':'')+(i<=g.farthest?'visited ':'')+(!g.footprints[i]&&i<g.farthest?'erased ':'')} aria-current={i===g.pos?'step':undefined}><span>{i===0?'⌂':i===g.pos?'●':i===10?'♜':i===6?'⚔':i}</span><small>{i===0?'入口':i===g.pos?`${i}歩`:i===10?'宝':i===6?'剣':''}</small></div>)}</nav>
   <div className="game-grid">
    <section className={'stage '+(ended?'result-stage':g.phase==='battle'?'battle-stage':'')} aria-live="polite">
     <div className="scene-eyebrow"><span>{ended?(g.phase==='won'?'JOURNEY COMPLETE':'TRY AGAIN'):g.returning?'THE WAY HOME':g.phase==='battle'?'CARD BATTLE':`${String(g.pos).padStart(2,'0')} / 10 STEPS`}</span><span>{g.sword?'⚔ 伝説の剣':''}{g.ten?'　✧ 10歩達成':''}</span></div>
     {ended?<><div className="result-mark">{g.phase==='won'?'✧':'☾'}</div><h1>{g.title}</h1><p className="result-copy">{g.phase==='won'?'お宝も、思い出も。ぜんぶ抱えて、ただいま。':'もう一歩の勇気と、引き返す勇気。次の旅で、また。'}</p><div className="result-score"><strong>{g.phase==='won'?scored.total:0}</strong><span>持ち帰った褒章</span></div><div className="score-list">{g.phase==='won'&&<><span>金銀財宝 <b>{scored.gold}</b></span><span>ラスボス <b>{scored.boss}</b></span><span>10歩達成 <b>{scored.ten}</b></span><span>羽の靴 <b>{scored.boots}</b></span><span>モンスター <b>{scored.monsters}</b></span></>}<span>最深到達 <b>{g.farthest}歩</b></span></div></>:
     <><div className="scene-heading"><h1>{g.title}</h1><p>{g.message}</p></div><button className="scene-card" onClick={()=>setModal('card')} aria-label="原作カードを大きく見る"><img src={card(g.art)} alt={g.title}/><span>＋ カードを拡大</span></button>{g.phase!=='battle'&&<p className={'return-hint '+(g.light<cost?'warning':'')}>⌂ 帰るための灯り <strong>{cost}</strong> {g.light<cost?'— このままでは足りない！':'を残しておこう'}</p>}</>}
    </section>
    <section className="commands" aria-label="いま選べる行動">
     {ended?<div className="ending-actions"><p className="eyebrow">{g.phase==='won'?`最高記録　${Math.max(best,scored.total)} 褒章`:'新しい迷宮が、待っている。'}</p><button className="primary" onClick={newGame}>もう一度、冒険へ <span>→</span></button><button className="secondary" onClick={share}>{copied?'結果をコピーしました':'冒険の結果をシェア'}</button><button className="text-button" onClick={()=>setModal('log')}>冒険を振り返る</button></div>:
     g.phase==='battle'&&enemy?<>
      <div className="command-top"><span className="eyebrow">どうする？</span><span className="cost-label">行動1回につき 灯り −1</span></div>
      <div className="battle-recipe">{!g.battle!.ambush&&enemy.quick.length>0&&<div><span className="recipe-label">一撃</span><Combo cards={enemy.quick}/></div>}<div><span className="recipe-label">{enemy.combo.length===1?'必要な札':`コンボ ${g.battle!.step+1}/${enemy.combo.length}`}</span><Combo cards={combo}/>{enemy.alternate&&g.battle!.step===0&&<span className="alternate"> または {LABELS[enemy.alternate]}</span>}</div></div>
      <div className="hand" aria-label="手札">{g.hand.map((s,i)=><button key={i} className={'hand-card '+s+(selected.includes(i)?' selected':'')} onClick={()=>{setSelected(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i]);setHint('')}} aria-label={`手札${i+1} ${LABELS[s]}`} aria-pressed={selected.includes(i)}><img src={card(s)} alt=""/><span>{LABELS[s]}</span><i>{selected.includes(i)?'✓':'＋'}</i></button>)}</div>
      <div className="play-row"><button className="primary play-button" disabled={!playKind(g,selected)} onClick={()=>act({type:'play',indices:selected})}>{playKind(g,selected)==='quick'?'一撃で倒す':selected.length?playKind(g,selected)?'このカードを出す':'組み合わせを選ぼう':'カードを選んでね'}<span>→</span></button><button className="secondary exchange" disabled={selected.length>1} onClick={()=>act({type:'exchange',index:selected[0]??0})} aria-label="選んだ1枚を交換">1枚交換<small>{selected.length===0?'左端の札を交換':'選んだ札を交換'}</small></button></div>
      <div className="tactics">{g.sword&&enemy.boss?<button onClick={()=>act({type:'legend'})}>⚔ 伝説の剣で一撃</button>:<button onClick={()=>{setSelected(suggested);setHint(suggested.length?'出せる組み合わせを選びました。':`今は出せる札がありません。不要な札を1枚選んで交換しよう。次に必要：${combo.map(s=>LABELS[s]).join('＋')}`)}}>✧ ヒント</button>}{g.captured.length>0&&!enemy.boss&&!g.battle!.ambush&&<button onClick={()=>act({type:'rescue'})}>仲間1体で相殺</button>}<button onClick={()=>act({type:'return'})}>引き返す</button></div>
      {hint&&<p className="inline-hint" role="status">{hint}</p>}
     </>:g.phase==='treasure'?<><div className="command-top"><span className="eyebrow">持ち帰る宝を選ぼう</span><span className="cost-label">選ぶだけなら灯り消費なし</span></div><div className="treasure-options">{(['gold','boots'] as const).map(t=><button key={t} onClick={()=>act({type:'treasure',kind:t})}><img src={card(t)} alt=""/><strong>{t==='gold'?'金銀財宝':'羽の靴'}</strong><span>{t==='gold'?'褒章5個。歩いて帰る。':'褒章1個。3歩ずつ飛んで帰る。'}</span></button>)}</div></>:
     <><div className="command-top"><span className="eyebrow">{g.returning?'さあ、おうちへ。':'どちらへ進む？'}</span><span className="cost-label">{g.returning?`入口まで ${g.pos}歩`:'進むと 灯り −1'}</span></div>
      {g.pos===6&&!g.sword&&<button className="sword-action" disabled={g.captured.length<3} onClick={()=>act({type:'legend'})}>⚔ {g.captured.length>=3?'伝説の剣を引き抜く　灯り −1':`剣を抜くには仲間あと${3-g.captured.length}体`}</button>}
      {g.returning?<div className="return-actions">{g.treasure==='boots'&&<button className="primary" onClick={()=>act({type:'fly'})}>羽の靴で{Math.min(3,g.pos)}歩戻る <span>−1 ✧</span></button>}<button className={g.treasure==='boots'?'secondary':'primary'} onClick={()=>act({type:'walk'})}>足跡をたどって1歩戻る <span>−{g.footprints[Math.max(0,g.pos-1)]?1:2} ✧</span></button></div>:<div className="route-options">{g.choices.map((r,i)=><button key={i} className={r.kind==='monster'?'risky':''} onClick={()=>act({type:'advance',choice:i})}><span className="route-icon">{roomGlyph(r)}</span><span><strong>{roomName(r)}</strong><small>{roomHint(r)}</small></span><span className="route-arrow">→</span></button>)}</div>}
      <div className="explore-bottom"><span>{g.returning?'持ち帰って、はじめて褒章。':g.pos===0?'6歩目に伝説の剣、10歩目に宝箱。':`仲間${g.captured.length}体 · ${g.sword?'伝説の剣あり':'仲間3体で伝説の剣'}`}</span>{g.pos>0&&!g.returning&&<button className="text-button" onClick={()=>act({type:'return'})}>ここで引き返す ↩</button>}</div>
     </>}
     <div className={'save-line '+(!saveOK?'save-error':'')}><span>{saveOK?'● この端末に自動保存':'保存できません。この画面を閉じずに遊んでください。'}</span>{!ended&&<button onClick={()=>setModal('restart')}>はじめから</button>}</div>
    </section>
   </div>
  </div>}
  {!active&&<footer>原作カードから生まれた、一人用の小さな冒険。</footer>}
  <dialog ref={dialog} className={'modal '+(modal==='card'?'card-modal':'')} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><div className="modal-header"><span>{modal==='help'?'ひとり旅のしおり':modal==='log'?'持ち物と冒険の記録':modal==='restart'?'新しい旅をはじめる？':'原作カード'}</span><button className="icon-button" onClick={()=>setModal(null)} aria-label="閉じる">×</button></div>
   {modal==='help'&&<div className="help-body"><p className="eyebrow">帰るまでが、冒険だ。</p><h2>宝物をねらって、<br/>無事に帰ってこよう。</h2><ol><li><b>道を選んで、最大10歩。</b>モンスターの道では仲間を増やせます。6歩目に剣、10歩目にラスボスと宝箱。</li><li><b>剣・盾・魔法でカードバトル。</b>画面の必要な札をタップして出します。「＋」は同時に2枚。「コンボ」は1ターンずつ。手札は自動補充。出せないときは1枚交換！</li><li><b>仲間3体で、伝説の剣。</b>6歩目で引き抜くと、ラスボスを一撃に。通常の敵には仲間1体を使って相殺もできます。</li><li><b>灯りが尽きる前に、入口へ。</b>灯りは36から。移動・戦闘・交換・剣を抜く行動で1減ります。実時間の制限はありません。途中で引き返しても大丈夫。</li><li><b>スライムと羽の靴。</b>スライムは手前の足跡を消します。消えた道は帰りの灯りが2倍。羽の靴なら灯り1で3歩戻れます。</li></ol><div className="help-score"><b>持ち帰った褒章で記録に挑戦</b><p>金銀財宝 5 ／ ラスボス 3 ／ 10歩達成 2 ／ 羽の靴 1<br/>いずれかがあれば、仲間1体につき ＋1。</p></div><h3>原作からの一人用アレンジ</h3><p>対人の競争・よこどり・カウントダウンを、灯りと帰還の判断に置き換えました。手札は4枚、道は毎回変わり、帰りの戦闘はありません。原作カードの細かな文面と異なる部分は、この画面のルールを使います。</p><p className="subtle">途中経過と最高記録は、この端末・このブラウザだけに保存します。音は最初OFF。遊び方を開いても灯りは減りません。</p></div>}
   {modal==='log'&&<div className="log-body"><div className="inventory"><span>⚔ 伝説の剣：{g.sword?'あり':'なし'}</span><span>♜ ラスボス：{g.boss?'撃破':'未撃破'}</span><span>✧ 宝：{g.treasure==='gold'?'金銀財宝':g.treasure==='boots'?'羽の靴':'なし'}</span><span>◈ 仲間：{g.captured.length}体</span></div><p className="subtle">{g.turn}回の行動 / 最高 {best}褒章</p><button className="text-button" onClick={()=>setModal('restart')}>新しい冒険をはじめる</button><ol>{g.log.map((line,i)=><li key={i}>{line}</li>)}</ol></div>}
   {modal==='restart'&&<div className="restart-body"><p>今の冒険を終えて、別の迷宮に出発します。最高記録は残ります。</p><button className="primary" onClick={newGame}>新しい冒険をはじめる →</button><button className="secondary" onClick={()=>setModal(null)}>今の冒険を続ける</button></div>}
   {modal==='card'&&<div className="large-card"><img src={card(g.art)} alt={g.title}/><p className="subtle">PDFの原作カードです。ゲーム中の処理は「ひとり旅のしおり」に従います。</p></div>}
  </dialog>
 </main>
}
